# Generated by Django 4.2.9 on 2024-02-27 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pId', models.CharField(max_length=10)),
                ('pName', models.CharField(max_length=20)),
                ('pCost', models.PositiveIntegerField()),
                ('pType', models.CharField(max_length=20)),
                ('pManu', models.CharField(max_length=20)),
                ('pLoc', models.CharField(max_length=20)),
                ('pQuantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oId', models.CharField(max_length=10)),
                ('oDate', models.DateField(blank=True, null=True)),
                ('oCost', models.PositiveIntegerField()),
                ('oClient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('oProduct', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.product')),
            ],
        ),
    ]
