# Generated by Django 4.2.9 on 2024-02-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_order_order_quantity_order_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pMenu',
            new_name='pManufacture',
        ),
    ]
