# Generated by Django 4.2.9 on 2024-02-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_rename_pmenu_product_pmanufacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pLoc',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
