# Generated by Django 4.2.9 on 2024-03-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_remove_order_oproduct_order_oproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='oProduct',
        ),
        migrations.AddField(
            model_name='order',
            name='oProduct',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
