# Generated by Django 4.2.9 on 2024-03-24 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_remove_order_oproduct_order_oproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='oDate',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
