# Generated by Django 4.2.9 on 2024-05-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_alter_feedback_feedback_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='oProduct',
        ),
        migrations.AddField(
            model_name='order',
            name='oProduct',
            field=models.ManyToManyField(to='quiz.product'),
        ),
    ]
